use crate::analysis::framework_registry::FrameworkEntry;

pub fn load_frameworks() -> Vec<FrameworkEntry> {
    vec![
        // RUST
        FrameworkEntry {
            name: "rust_stdlib".to_string(),
            language: "rust".to_string(),
            root_patterns: vec![
                "fn main()".to_string(),
                "#[tokio::main]".to_string(),
                "#[async_std::main]".to_string(),
                "#[actix_web::main]".to_string(),
            ],
            decorator_patterns: vec![
                "#[derive".to_string(),
                "#[serde".to_string(),
                "#[wasm_bindgen".to_string(),
            ],
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "#[no_mangle]".to_string(),
                "#[export_name".to_string(),
                "#[link_name".to_string(),
            ],
            generated_entrypoints: vec!["build.rs".to_string()],
            dynamic_behavior: vec![
                "Box<dyn".to_string(),
                "&dyn".to_string(),
                "extern \"C\"".to_string(),
                "fn pointer".to_string(),
            ],
        },
        FrameworkEntry {
            name: "yew".to_string(),
            language: "rust".to_string(),
            root_patterns: vec!["#[function_component]".to_string()],
            decorator_patterns: vec!["#[function_component]".to_string()],
            annotation_patterns: Vec::new(),
            registration_patterns: vec!["yew::start_app".to_string(), "yew::Renderer".to_string()],
            generated_entrypoints: Vec::new(),
            dynamic_behavior: vec!["html!".to_string(), "Callback::from".to_string()],
        },
        FrameworkEntry {
            name: "tauri".to_string(),
            language: "rust".to_string(),
            root_patterns: vec![
                "fn main()".to_string(),
                "tauri::Builder".to_string(),
                "tauri::generate_context".to_string(),
            ],
            decorator_patterns: vec!["#[tauri::command]".to_string()],
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "invoke_handler".to_string(),
                "tauri::generate_handler".to_string(),
                ".run(".to_string(),
                "expect".to_string(),
            ],
            generated_entrypoints: vec!["tauri.conf.json".to_string(), "src-tauri/".to_string()],
            dynamic_behavior: vec![
                "invoke".to_string(),
                "emit".to_string(),
                "listen".to_string(),
                "window".to_string(),
                "webview".to_string(),
            ],
        },
        // PYTHON
        FrameworkEntry {
            name: "flask".to_string(),
            language: "python".to_string(),
            root_patterns: vec![
                "@app.route".to_string(),
                "@app.get".to_string(),
                "@app.post".to_string(),
            ],
            decorator_patterns: vec![
                "@app.route".to_string(),
                "@app.before_request".to_string(),
                "@app.teardown_request".to_string(),
                "@app.errorhandler".to_string(),
            ],
            annotation_patterns: Vec::new(),
            registration_patterns: vec!["app.register_blueprint".to_string()],
            generated_entrypoints: Vec::new(),
            dynamic_behavior: vec![
                "url_for".to_string(),
                "getattr".to_string(),
                "__import__".to_string(),
            ],
        },
        FrameworkEntry {
            name: "django".to_string(),
            language: "python".to_string(),
            root_patterns: vec![
                "def view".to_string(),
                "class View".to_string(),
                "class APIView".to_string(),
            ],
            decorator_patterns: vec![
                "@login_required".to_string(),
                "@permission_required".to_string(),
            ],
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "urlpatterns".to_string(),
                "path(".to_string(),
                "re_path(".to_string(),
            ],
            generated_entrypoints: vec!["manage.py".to_string()],
            dynamic_behavior: vec!["getattr".to_string(), "import_module".to_string()],
        },
        FrameworkEntry {
            name: "fastapi".to_string(),
            language: "python".to_string(),
            root_patterns: vec![
                "@app.get".to_string(),
                "@app.post".to_string(),
                "@app.put".to_string(),
                "@app.delete".to_string(),
                "@app.patch".to_string(),
            ],
            decorator_patterns: vec!["@app.middleware".to_string(), "@app.on_event".to_string()],
            annotation_patterns: Vec::new(),
            registration_patterns: vec!["APIRouter".to_string(), "include_router".to_string()],
            generated_entrypoints: Vec::new(),
            dynamic_behavior: vec!["Depends".to_string(), "BackgroundTasks".to_string()],
        },
        // JAVASCRIPT
        FrameworkEntry {
            name: "react".to_string(),
            language: "javascript".to_string(),
            root_patterns: vec![
                "export default function".to_string(),
                "export function".to_string(),
                "export const".to_string(),
            ],
            decorator_patterns: vec!["@connect".to_string(), "@withRouter".to_string()],
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "ReactDOM.render".to_string(),
                "createRoot".to_string(),
                "hydrateRoot".to_string(),
            ],
            generated_entrypoints: Vec::new(),
            dynamic_behavior: vec![
                "useEffect".to_string(),
                "useCallback".to_string(),
                "React.lazy".to_string(),
                "import(".to_string(),
            ],
        },
        FrameworkEntry {
            name: "express".to_string(),
            language: "javascript".to_string(),
            root_patterns: vec![
                "app.get".to_string(),
                "app.post".to_string(),
                "app.put".to_string(),
                "app.delete".to_string(),
                "app.use".to_string(),
            ],
            decorator_patterns: Vec::new(),
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "express()".to_string(),
                "app.listen".to_string(),
                "router.get".to_string(),
            ],
            generated_entrypoints: Vec::new(),
            dynamic_behavior: vec![
                "require".to_string(),
                "import(".to_string(),
                "eval".to_string(),
            ],
        },
        FrameworkEntry {
            name: "nextjs".to_string(),
            language: "javascript".to_string(),
            root_patterns: vec![
                "export default".to_string(),
                "export async function".to_string(),
            ],
            decorator_patterns: Vec::new(),
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "getServerSideProps".to_string(),
                "getStaticProps".to_string(),
                "getStaticPaths".to_string(),
            ],
            generated_entrypoints: vec!["pages/".to_string(), "app/".to_string()],
            dynamic_behavior: vec!["dynamic(".to_string(), "import(".to_string()],
        },
        // TYPESCRIPT
        FrameworkEntry {
            name: "angular".to_string(),
            language: "typescript".to_string(),
            root_patterns: vec!["export class".to_string()],
            decorator_patterns: vec![
                "@Component".to_string(),
                "@Directive".to_string(),
                "@Pipe".to_string(),
                "@Injectable".to_string(),
                "@NgModule".to_string(),
            ],
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "bootstrapModule".to_string(),
                "platformBrowserDynamic".to_string(),
            ],
            generated_entrypoints: vec!["main.ts".to_string()],
            dynamic_behavior: vec!["inject(".to_string(), "new InjectionToken".to_string()],
        },
        FrameworkEntry {
            name: "nestjs".to_string(),
            language: "typescript".to_string(),
            root_patterns: vec!["export class".to_string()],
            decorator_patterns: vec![
                "@Controller".to_string(),
                "@Module".to_string(),
                "@Injectable".to_string(),
                "@Get".to_string(),
                "@Post".to_string(),
                "@Put".to_string(),
                "@Delete".to_string(),
            ],
            annotation_patterns: Vec::new(),
            registration_patterns: vec!["NestFactory.create".to_string(), "@Inject".to_string()],
            generated_entrypoints: vec!["main.ts".to_string()],
            dynamic_behavior: vec!["@Inject".to_string(), "forwardRef".to_string()],
        },
        FrameworkEntry {
            name: "react".to_string(),
            language: "typescript".to_string(),
            root_patterns: vec![
                "export default function".to_string(),
                "export function".to_string(),
                "export const".to_string(),
                "export default class".to_string(),
            ],
            decorator_patterns: vec![
                "@connect".to_string(),
                "@withRouter".to_string(),
                "@observer".to_string(),
            ],
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "ReactDOM.render".to_string(),
                "createRoot".to_string(),
                "hydrateRoot".to_string(),
                "ReactDOM.createRoot".to_string(),
            ],
            generated_entrypoints: vec!["pages/".to_string(), "app/".to_string()],
            dynamic_behavior: vec![
                "useEffect".to_string(),
                "useCallback".to_string(),
                "useMemo".to_string(),
                "useState".to_string(),
                "useRef".to_string(),
                "React.lazy".to_string(),
                "import(".to_string(),
                "forwardRef".to_string(),
                "memo".to_string(),
            ],
        },
        // GO
        FrameworkEntry {
            name: "go_stdlib".to_string(),
            language: "go".to_string(),
            root_patterns: vec!["func main()".to_string(), "func init()".to_string()],
            decorator_patterns: Vec::new(),
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "http.HandleFunc".to_string(),
                "http.ListenAndServe".to_string(),
                "rpc.Register".to_string(),
            ],
            generated_entrypoints: vec!["cmd/".to_string()],
            dynamic_behavior: vec![
                "go func".to_string(),
                "reflect".to_string(),
                "interface{}".to_string(),
            ],
        },
        FrameworkEntry {
            name: "gin".to_string(),
            language: "go".to_string(),
            root_patterns: vec!["func main()".to_string()],
            decorator_patterns: Vec::new(),
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "gin.Default".to_string(),
                "gin.New".to_string(),
                "router.GET".to_string(),
                "router.POST".to_string(),
            ],
            generated_entrypoints: Vec::new(),
            dynamic_behavior: vec!["c.ShouldBind".to_string(), "c.Param".to_string()],
        },
        // JAVA
        FrameworkEntry {
            name: "spring".to_string(),
            language: "java".to_string(),
            root_patterns: vec!["public static void main".to_string()],
            decorator_patterns: Vec::new(),
            annotation_patterns: vec![
                "@Controller".to_string(),
                "@RestController".to_string(),
                "@Service".to_string(),
                "@Component".to_string(),
                "@Repository".to_string(),
                "@Configuration".to_string(),
            ],
            registration_patterns: vec![
                "@Bean".to_string(),
                "@Autowired".to_string(),
                "@Value".to_string(),
            ],
            generated_entrypoints: Vec::new(),
            dynamic_behavior: vec![
                "@Transactional".to_string(),
                "@Async".to_string(),
                "ApplicationContext".to_string(),
                "Class.forName".to_string(),
            ],
        },
        FrameworkEntry {
            name: "android".to_string(),
            language: "java".to_string(),
            root_patterns: vec![
                "onCreate".to_string(),
                "onStart".to_string(),
                "onResume".to_string(),
            ],
            decorator_patterns: Vec::new(),
            annotation_patterns: vec!["@Override".to_string(), "@SuppressLint".to_string()],
            registration_patterns: vec!["setContentView".to_string(), "startActivity".to_string()],
            generated_entrypoints: vec!["R.layout".to_string(), "AndroidManifest.xml".to_string()],
            dynamic_behavior: vec![
                "findViewById".to_string(),
                "Intent".to_string(),
                "BroadcastReceiver".to_string(),
            ],
        },
        // DART
        FrameworkEntry {
            name: "flutter".to_string(),
            language: "dart".to_string(),
            root_patterns: vec!["void main()".to_string(), "Future<void> main".to_string()],
            decorator_patterns: vec!["@override".to_string(), "@protected".to_string()],
            annotation_patterns: vec!["@override".to_string(), "@required".to_string()],
            registration_patterns: vec![
                "runApp".to_string(),
                "MaterialApp".to_string(),
                "CupertinoApp".to_string(),
            ],
            generated_entrypoints: vec!["lib/main.dart".to_string()],
            dynamic_behavior: vec![
                "Navigator.push".to_string(),
                "showDialog".to_string(),
                "setState".to_string(),
            ],
        },
        // PHP
        FrameworkEntry {
            name: "laravel".to_string(),
            language: "php".to_string(),
            root_patterns: vec![
                "function __construct".to_string(),
                "function handle".to_string(),
            ],
            decorator_patterns: vec!["@middleware".to_string()],
            annotation_patterns: vec!["@Route".to_string(), "@Middleware".to_string()],
            registration_patterns: vec![
                "Route::get".to_string(),
                "Route::post".to_string(),
                "Route::resource".to_string(),
                "Artisan::command".to_string(),
            ],
            generated_entrypoints: vec!["routes/web.php".to_string(), "routes/api.php".to_string()],
            dynamic_behavior: vec![
                "app(".to_string(),
                "resolve".to_string(),
                "event(".to_string(),
            ],
        },
        FrameworkEntry {
            name: "symfony".to_string(),
            language: "php".to_string(),
            root_patterns: vec![
                "function __invoke".to_string(),
                "function execute".to_string(),
            ],
            decorator_patterns: Vec::new(),
            annotation_patterns: vec!["@Route".to_string(), "@Security".to_string()],
            registration_patterns: vec![
                "services.yaml".to_string(),
                "autowire".to_string(),
                "autoconfigure".to_string(),
            ],
            generated_entrypoints: vec!["public/index.php".to_string()],
            dynamic_behavior: vec!["container->get".to_string(), "EventDispatcher".to_string()],
        },
        // CPP
        FrameworkEntry {
            name: "cpp_stdlib".to_string(),
            language: "cpp".to_string(),
            root_patterns: vec![
                "int main".to_string(),
                "void main".to_string(),
                "wmain".to_string(),
                "WinMain".to_string(),
            ],
            decorator_patterns: Vec::new(),
            annotation_patterns: Vec::new(),
            registration_patterns: vec![
                "extern \"C\"".to_string(),
                "__declspec(dllexport)".to_string(),
                "JNIEXPORT".to_string(),
            ],
            generated_entrypoints: vec!["CMakeLists.txt".to_string()],
            dynamic_behavior: vec![
                "virtual".to_string(),
                "std::function".to_string(),
                "dlopen".to_string(),
                "dlsym".to_string(),
            ],
        },
        FrameworkEntry {
            name: "qt".to_string(),
            language: "cpp".to_string(),
            root_patterns: vec!["int main".to_string()],
            decorator_patterns: Vec::new(),
            annotation_patterns: vec![
                "Q_OBJECT".to_string(),
                "Q_INVOKABLE".to_string(),
                "signals:".to_string(),
                "slots:".to_string(),
            ],
            registration_patterns: vec![
                "QApplication".to_string(),
                "qmlRegisterType".to_string(),
                "QObject::connect".to_string(),
            ],
            generated_entrypoints: vec!["moc_".to_string()],
            dynamic_behavior: vec![
                "QMetaObject".to_string(),
                "invokeMethod".to_string(),
                "Q_EMIT".to_string(),
            ],
        },
        // CSHARP
        FrameworkEntry {
            name: "aspnet".to_string(),
            language: "csharp".to_string(),
            root_patterns: vec![
                "static void Main".to_string(),
                "static async Task Main".to_string(),
            ],
            decorator_patterns: vec![
                "[ApiController]".to_string(),
                "[Route".to_string(),
                "[HttpPost".to_string(),
                "[HttpGet".to_string(),
            ],
            annotation_patterns: vec!["[ApiController]".to_string(), "[Route".to_string()],
            registration_patterns: vec![
                "app.MapController".to_string(),
                "app.MapGet".to_string(),
                "app.MapPost".to_string(),
                "builder.Services.Add".to_string(),
            ],
            generated_entrypoints: vec!["Program.cs".to_string(), "Startup.cs".to_string()],
            dynamic_behavior: vec![
                "reflection".to_string(),
                "Activator.CreateInstance".to_string(),
                "dynamic".to_string(),
            ],
        },
        FrameworkEntry {
            name: "unity".to_string(),
            language: "csharp".to_string(),
            root_patterns: vec![
                "void Awake".to_string(),
                "void Start".to_string(),
                "void Update".to_string(),
                "void FixedUpdate".to_string(),
            ],
            decorator_patterns: Vec::new(),
            annotation_patterns: vec![
                "[SerializeField]".to_string(),
                "[RequireComponent]".to_string(),
            ],
            registration_patterns: vec![
                "gameObject.AddComponent".to_string(),
                "Instantiate".to_string(),
            ],
            generated_entrypoints: vec!["Assets/".to_string()],
            dynamic_behavior: vec![
                "GetComponent".to_string(),
                "SendMessage".to_string(),
                "Invoke".to_string(),
            ],
        },
    ]
}
